# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sdkDemo
pod 'RTBEquipmentInfo_iOS'
  target 'sdkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sdkDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
